services:
    server:
        container_name: my-web-app
        build:
            dockerfile: Dockerfile.dev
            context: ./
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
        ports:
            - 3000:3000
        command: bash -c "air && npx  @tailwindcss/cli -i ./static/input.css -o ./static/output.css --watch"
        # env_file:
        #     - ./.env
