FROM golang:1.23.6

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Install templ
RUN go install github.com/a-h/templ/cmd/templ@latest

# Install node js for tailwindcss
RUN apt-get update && apt-get install -y curl 
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && . "$HOME/.nvm/nvm.sh" \
    && nvm install 22 \
    && npm install -g tailwindcss @tailwindcss/cli 

# Ensure go app binaries are in the path
ENV PATH="/go/bin:${PATH}"

# set working directory
WORKDIR /app

# Copies local files to the docker container
COPY . .

RUN go mod tidy

# RUN go build -o ./cmd/main ./cmd/main.go

EXPOSE 3000
